### ISSUE TITLE
Object is not a constructor (evaluating 'new _otpClient.default(secret)')

### ISSUE THREAD

**Issue by jrwmacedo** [olsio/otp-client#1]
Hello @olsio , everything is ok ?
Thanks for your library, I am trying to use it together react-native but I am facing the following issue, maybe you could help to solve.

The exception is:

Object is not a constructor (evaluating 'new _otpClient.default(secret)')

The example code that i am using is:

`import React, {Component} from 'react';
import {View, Text} from 'react-native';
import OTP from 'otp-client';
 
const secret = 'TPQDAHVBZ5NBO5LFEQKC7V7UPATSSMFY';
const otp = new OTP(secret);
const token = otp.getToken() ;// e.g. 624343
export default class TokenManagement extends Component {
 
 
render = () => {
   return( <View>
        <Text>{token}</Text>

    </View>)
}

};`

Thanks a lot for your time and support.

**Comment by olsio** [comment]
I am upgrading all lib versions and will try to reproduce it in Expo.

**Comment by olsio** [comment]
I think the problem is with the webpack 4 output vs the previous webpack 3. I hope to find some time later this evening to investigate further.

**Comment by olsio** [comment]
I switched back to webpack 3 and it works fine now. Update your package.json to version 1.0.1 and it should work.

**Comment by jrwmacedo** [comment]
Thanks man, it's working!
